[package]
name = "vagrant-to-ansible"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "v2a"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.7"
serde = { version = "1.0.192", features = ["derive"] }
serde_yaml = "0.9.27"
ssh2-config = "0.2.2"
