on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  lint: # ----------------------------------------------------------------------
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - id: clippy
        name: clippy
        run: cargo clippy --all --all-targets
      - id: format
        name: format
        run: cargo fmt --all -- --check
  test: # ----------------------------------------------------------------------
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    env:
      RUSTFLAGS: --deny warnings
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - id: build
        name: build
        uses: actions-rs/cargo@v1
        with:
          command: build # required for end-to-end tests in main.rs
      - id: test
        name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-fail-fast
