on:
  push:
    tags:
      - '*'
defaults:
  run:
    shell: bash
jobs:
  release:
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - aarch64-unknown-linux-musl
          - arm-unknown-linux-musleabihf
          - armv7-unknown-linux-musleabihf
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-musl
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
            target_rustflags: ''
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            target_rustflags: '--codegen linker=aarch64-linux-gnu-gcc'
          - target: arm-unknown-linux-musleabihf
            os: ubuntu-latest
            target_rustflags: '--codegen linker=arm-linux-gnueabihf-gcc'
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
            target_rustflags: '--codegen linker=arm-linux-gnueabihf-gcc'
          - target: x86_64-apple-darwin
            os: macos-latest
            target_rustflags: ''
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            target_rustflags: ''
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            target_rustflags: ''
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal
          target: ${{ matrix.target }}
      - name: install aarch64 toolchain
        if: ${{ matrix.target == 'aarch64-unknown-linux-musl' }}
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu
      - name: install arm toolchain
        if: ${{ matrix.target == 'arm-unknown-linux-musleabihf' || matrix.target == 'armv7-unknown-linux-musleabihf' }}
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabihf
      - name: package
        id: package
        env:
          TARGET: ${{ matrix.target }}
          REF: ${{ github.ref }}
          OS: ${{ matrix.os }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
        run: ./bin/package
        shell: bash
      - name: publish archive
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: ${{ steps.package.outputs.archive }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish changelog
        uses: softprops/action-gh-release@v1
        if: >-
          ${{startsWith(github.ref, 'refs/tags/') && matrix.target == 'x86_64-unknown-linux-musl'}}
        with:
          files: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: generate checksums
        uses: wangzuo/action-release-checksums@v1
